# Generated by Django 3.1.1 on 2020-09-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
    ]
