# Generated by Django 3.1.1 on 2020-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
