# Generated by Django 3.1.1 on 2020-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_subreddit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
