# Generated by Django 2.0 on 2020-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
